import { Mesh, MeshBuilder, Scene, TransformNode, Vector3 } from "@babylonjs/core";
import { createCampusMaterials } from "../materials/materials";
import { tryAttachModel } from "../assets/modelLoader";
import { aheadFactor, MovingObstacle } from "./collisionAvoidance";
import { v3 } from "./pathTypes";
import { vehicleRoutes } from "./trafficRoutes";
import { createRouteDebugLines } from "./routeDebug";
import { VehicleState, VehicleType } from "./vehicleTypes";

type Vehicle = MovingObstacle & { type:VehicleType; root:TransformNode; wheels:Mesh[]; routeIndex:number; currentSegment:number; target:number; speed:number; maxSpeed:number; safeDistance:number; waitTimer:number; state:VehicleState; phase:number };
export type VehicleSystem = { vehicles: Vehicle[]; setPaused(v:boolean):void; setDebugVisible(v:boolean):void; getStats():{count:number; paused:boolean; yielding:number; cityFlow:string}; dispose():void };
const fleet:VehicleType[]=[...Array(6).fill("car"),"bus",...Array(5).fill("van"),...Array(8).fill("car"),...Array(3).fill("truck"),...Array(4).fill("forklift")];
export function createVehicleSystem(scene:Scene, materials:ReturnType<typeof createCampusMaterials>, pedestrians:MovingObstacle[]):VehicleSystem{let paused=false; const vehicles:Vehicle[]=[]; const debug=createRouteDebugLines(scene,vehicleRoutes,"车辆路线");
 const dims=(t:VehicleType)=>t==="truck"?new Vector3(3.2,2.4,8):t==="bus"?new Vector3(3,2.8,10):t==="forklift"?new Vector3(1.5,1.5,2.6):new Vector3(2.1,1.35,4.2);
 const make=(i:number,type:VehicleType,routeIndex:number)=>{const r=vehicleRoutes[routeIndex]; const root=new TransformNode(`动态车辆-${type}-${i}`,scene); root.position=v3(r.points[i%r.points.length]); const d=dims(type); const body=MeshBuilder.CreateBox(`${root.name}-body`,{width:d.x,height:d.y,depth:d.z},scene); body.position.y=d.y/2+.25; body.material=type==="truck"?materials.steel:type==="forklift"?materials.equipment:materials.dark; body.parent=root; const cab=MeshBuilder.CreateBox(`${root.name}-cab`,{width:d.x*.78,height:d.y*.55,depth:d.z*.35},scene); cab.position.set(0,d.y+.45,-d.z*.12); cab.material=materials.glass; cab.parent=root; const wheels:Mesh[]=[]; for(const x of [-d.x*.46,d.x*.46]) for(const z of [-d.z*.34,d.z*.34]){const w=MeshBuilder.CreateCylinder(`${root.name}-wheel`,{diameter:.55,height:.32,tessellation:12},scene); w.rotation.z=Math.PI/2; w.position.set(x,.42,z); w.material=materials.road; w.parent=root; wheels.push(w);} void tryAttachModel(scene,type,root,[body,cab,...wheels]); vehicles.push({id:root.name,type,root,wheels,position:root.position,radius:Math.max(d.x,d.z)*.55,routeId:r.id,routeIndex,currentSegment:0,target:(i+1)%r.points.length,speed:0,maxSpeed:type==="forklift"?3:type==="truck"?7:10+(i%4),safeDistance:type==="forklift"?5:10,waitTimer:0,state:"driving",phase:i});};
 fleet.forEach((t,i)=>make(i,t,i<12?i%2:i<20?3:i<23?5:6));
 const step=()=>{const dt=Math.min(scene.getEngine().getDeltaTime()/1000,.05); if(paused)return; for(const v of vehicles){const route=vehicleRoutes[v.routeIndex], target=v3(route.points[v.target]); const delta=target.subtract(v.root.position); if(delta.length()<1.2){v.currentSegment=v.target; v.target=(v.target+1)%route.points.length;} const dir=target.subtract(v.root.position).normalize(); let hazard=0; for(const p of pedestrians) hazard=Math.max(hazard,aheadFactor(v.root.position,dir,p.position,v.safeDistance+10,3.2)); for(const other of vehicles) if(other!==v) hazard=Math.max(hazard,aheadFactor(v.root.position,dir,other.root.position,v.safeDistance+other.radius,2.8)); const desired=hazard>.65?0:hazard>.2?v.maxSpeed*.28:v.maxSpeed; v.speed += (desired-v.speed)*Math.min(1,dt*3.5); v.state=desired===0?"stopped":hazard>.2?"yielding":"driving"; v.root.position.addInPlace(dir.scale(v.speed*dt)); v.position=v.root.position; v.root.rotation.y=Math.atan2(dir.x,dir.z); v.phase+=v.speed*dt; v.wheels.forEach(w=>w.rotation.x+=v.speed*dt*2.6); }};
 scene.onBeforeRenderObservable.add(step);
 return {vehicles,setPaused:v=>paused=v,setDebugVisible:v=>debug.forEach(d=>d.isVisible=v),getStats:()=>({count:vehicles.length,paused,yielding:vehicles.filter(v=>v.state!=="driving").length,cityFlow:vehicles.some(v=>v.routeId?.startsWith("city")&&v.state==="stopped")?"斑马线让行":"双向通行"}),dispose:()=>scene.onBeforeRenderObservable.removeCallback(step)};
}
