import { Mesh, Scene, Vector3 } from "@babylonjs/core";
import { BuildingSpec } from "../buildings/buildingTypes";
import { createCameraController } from "../camera/cameraController";
import { createBlockAvatar } from "./createBlockAvatar";
import { DEFAULT_WALK_SPEED, EYE_HEIGHT, MAX_WALK_SPEED, MIN_WALK_SPEED, PLAYER_HEIGHT, SHIFT_SPEED_MULTIPLIER, playerCenterYForFloor } from "./playerConstants";

export const createPlayerController=(scene:Scene,cameras:ReturnType<typeof createCameraController>,player: Mesh,buildings:BuildingSpec[],onLocation:(s:string)=>void)=>{
 let walk=DEFAULT_WALK_SPEED,lastYaw=0,currentBuilding:BuildingSpec|undefined,currentFloor=0;const keys=new Set<string>();const avatar=createBlockAvatar(scene);avatar.root.parent=player;avatar.setVisible(false);
 const entrancePoint=(b:BuildingSpec,inside:boolean,floor=0)=>new Vector3(b.position.x,playerCenterYForFloor(floor,b.floorHeight),b.position.z+b.size.depth/2+(inside?-8:12));
 const elevatorPoint=(b:BuildingSpec,floor:number)=>new Vector3(b.position.x+b.size.width/2-8,playerCenterYForFloor(floor,b.floorHeight),b.position.z-b.size.depth/2+14);
 const place=(p:Vector3,yaw:number,inside=false)=>{player.position.copyFrom(p);cameras.syncTo(p,yaw,inside);};
 const goTo=(b:BuildingSpec,inside:boolean)=>{currentBuilding=inside?b:undefined;currentFloor=0;const p=entrancePoint(b,inside);place(p,inside?Math.PI:0,inside);onLocation(inside?`${b.name} · 1层 · ${b.zone} · ${b.description}`:`${b.name}门前 · 面向入口`);cameras.setViewMode("first");};
 const resetToEntrance=()=>{currentBuilding=undefined;currentFloor=0;place(new Vector3(0,PLAYER_HEIGHT/2,-430),0,false);onLocation("主入口 · 室外园区");cameras.setViewMode("first");};
 const getPlanarMoveBasisForActiveCamera=()=>{const cam=cameras.viewMode==="first"?cameras.first:cameras.viewMode==="third"?cameras.third:cameras.overhead;let forward=cam.getForwardRay().direction.clone();forward.y=0;if(forward.lengthSquared()<.0001)forward=new Vector3(Math.sin((cam as any).alpha||0),0,Math.cos((cam as any).alpha||0));forward.normalize();if(cameras.viewMode==="first")forward.scaleInPlace(-1);const right=Vector3.Cross(Vector3.Up(),forward).normalize();return {forward,right};};
 window.addEventListener("keydown",e=>{keys.add(e.code); if(e.code==="KeyV")cameras.setViewMode(cameras.viewMode==="first"?"third":cameras.viewMode==="third"?"overhead":"first"); if(e.code==="KeyE"){const b=buildings.find(b=>Vector3.Distance(player.position,entrancePoint(b,false))<11);if(b)goTo(b,true);} if(e.code==="KeyF"){const b=currentBuilding ?? buildings.find(b=>b.hasElevator&&Math.abs(player.position.x-(b.position.x+b.size.width/2-8))<8&&Math.abs(player.position.z-(b.position.z-b.size.depth/2+14))<8);if(b?.hasElevator){currentBuilding=b;currentFloor=(currentFloor+1)%b.floors;const p=elevatorPoint(b,currentFloor);place(p,Math.PI,true);onLocation(`${b.name} · ${currentFloor+1}层电梯厅 · ${b.zone}`);}} if(e.code==="KeyR")resetToEntrance();});window.addEventListener("keyup",e=>keys.delete(e.code));
 scene.onBeforeRenderObservable.add(()=>{const dt=scene.getEngine().getDeltaTime()/1000;const speed=walk*(keys.has("ShiftLeft")||keys.has("ShiftRight")?SHIFT_SPEED_MULTIPLIER:1);const {forward,right}=getPlanarMoveBasisForActiveCamera();const d=Vector3.Zero();if(keys.has("KeyW")||keys.has("ArrowUp"))d.addInPlace(forward);if(keys.has("KeyS")||keys.has("ArrowDown"))d.subtractInPlace(forward);if(keys.has("KeyD")||keys.has("ArrowRight"))d.addInPlace(right);if(keys.has("KeyA")||keys.has("ArrowLeft"))d.subtractInPlace(right);if(d.lengthSquared()>0){d.normalize();lastYaw=Math.atan2(d.x,d.z);const move=d.scale(speed*dt);player.moveWithCollisions(move);if(cameras.viewMode==="first")cameras.first.position.copyFrom(player.position).addInPlaceFromFloats(0,EYE_HEIGHT-PLAYER_HEIGHT/2,0);}avatar.setYaw(lastYaw);avatar.setVisible(cameras.viewMode!=="first");cameras.syncTargets();});
 return {player,goTo,resetToEntrance,getPlanarMoveBasisForActiveCamera,setWalkSpeed:(v:number)=>walk=Math.min(MAX_WALK_SPEED,Math.max(MIN_WALK_SPEED,v)),getWalkSpeed:()=>walk};
};
